CREATE TABLE [dbo].[HelloWorld]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Text] NVARCHAR(200) NOT NULL,
	[CreatedBy] NVARCHAR(200) NOT NULL,
	[Created] DATETIME2(7) NOT NULL,
	[UpdatedBy] NVARCHAR(200) NOT NULL,
	[Updated] DATETIME2(7) NOT NULL,
	[RowVersion] ROWVERSION NOT NULL

)
GO

ALTER TABLE [dbo].[HelloWorld] ADD  CONSTRAINT [PK_HelloWorld] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
) 
GO

ALTER TABLE [dbo].[HelloWorld] ADD CONSTRAINT DF_HelloWorld_Created DEFAULT GETUTCDATE() FOR [Created];
GO

ALTER TABLE [dbo].[HelloWorld] ADD CONSTRAINT DF_HelloWorld_Updated DEFAULT GETUTCDATE() FOR [Updated];
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_HelloWorld_Text] ON [dbo].[HelloWorld]
(
	[Text] ASC
)
GO
