global using Xunit;
global using Domain.Wini.Entities;
global using Domain.Wini.Values;
global using Domain.Wini.Enums;
global using Domain.Wini.Models;
global using Domain.Wini.Exceptions;
global using Domain.Wini.Interfaces;
global using Domain.Wini.Aggregates;
global using FluentValidation;