global using Domain.Entities;
global using Domain.Values;
global using Domain.Enums;
global using Domain.Models;
global using Domain.Exceptions;
global using Domain.Interfaces;
global using Domain.ErrorCodes;
global using Domain.Aggregates;
global using FluentValidation;